# Generated by Django 5.2.6 on 2025-10-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BusinessCriticalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greet_intro', models.IntegerField()),
                ('greet_intro_pg', models.IntegerField()),
                ('greet_intro_agent_intro', models.IntegerField()),
                ('cust_verf', models.IntegerField()),
                ('cust_verf_correct', models.IntegerField()),
                ('cust_verf_acc', models.IntegerField()),
                ('call_purp', models.IntegerField()),
                ('call_purp_clear', models.IntegerField()),
                ('call_purp_tone', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_metrics', to='backend.agentevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCriticalErrorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('comment', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_error_metrics', to='backend.agentevaluation')),
            ],
        ),
    ]
