# Generated by Django 5.2.6 on 2025-10-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_agentevaluation_alter_audiofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='call_purp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='call_purp_clear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='call_purp_tone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='cust_verf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='cust_verf_acc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='cust_verf_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='greet_intro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='greet_intro_agent_intro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='greet_intro_pg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesscriticalmetric',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customercriticalerrormetric',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customercriticalerrormetric',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
