# Generated by Django 5.2.7 on 2025-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_businesscriticalmetric_call_purp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
