# Generated by Django 5.2.7 on 2025-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_audiofile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentevaluation',
            name='file_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='agentevaluation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
